WebApp/Gaming/Models/CustomVm.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Gaming.Models;

public class CustomVm
{
    [Key] public string Login { get; set; }
    [Required] [DataType(DataType.Password)] public string? Password { get; set; }
    [ReadOnly(true)] public string? Name { get; set; }
    [ReadOnly(true)] public string? Ip { get; set; }
    [ReadOnly(true)] public bool IsStarted { get; set; }
    
}

WebApp/Gaming/Models/ErrorViewModel.cs
namespace Gaming.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp/Gaming/Controllers/CustomVmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gaming.Data;
using Gaming.Models;
using Gaming.Services;

namespace Gaming.Controllers
{
    public class CustomVmController : Controller
    {
        private readonly ApplicationDbContext _context;
        AzureVmService azureVmService = new();

        public CustomVmController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CustomVm
        public async Task<IActionResult> Index()
        {
              return _context.CustomVms != null ? 
                          View(await _context.CustomVms.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.CustomVms'  is null.");
        }

        // GET: CustomVm/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.CustomVms == null)
            {
                return NotFound();
            }

            var customVm = await _context.CustomVms
                .FirstOrDefaultAsync(m => m.Login == id);
            if (customVm == null)
            {
                return NotFound();
            }

            return View(customVm);
        }

        // GET: CustomVm/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CustomVm/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Login,Password")] CustomVm customVm)
        {
            if (!ModelState.IsValid) return View(customVm);
            
            await azureVmService.CreateAzureVm(customVm);
            _context.Add(customVm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: CustomVm/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.CustomVms == null)
            {
                return NotFound();
            }

            var customVm = await _context.CustomVms.FindAsync(id);
            if (customVm == null)
            {
                return NotFound();
            }
            return View(customVm);
        }

        // POST: CustomVm/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Login,Password,Name,Ip,IsStarted")] CustomVm customVm)
        {
            if (id != customVm.Login)
            {
                return NotFound();
            }

            if (!ModelState.IsValid) return View(customVm);
            try
            {
                _context.Update(customVm);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CustomVmExists(customVm.Login))
                {
                    return NotFound();
                }

                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: CustomVm/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.CustomVms == null)
            {
                return NotFound();
            }

            var customVm = await _context.CustomVms
                .FirstOrDefaultAsync(m => m.Login == id);
            if (customVm == null)
            {
                return NotFound();
            }

            return View(customVm);
        }

        // POST: CustomVm/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.CustomVms == null)
            {
                return Problem("Entity set 'ApplicationDbContext.CustomVms'  is null.");
            }
            var customVm = await _context.CustomVms.FindAsync(id);
            await azureVmService.DeleteAzureVm(id);
            if (customVm != null)
            {
                _context.CustomVms.Remove(customVm);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        /// <summary>
        /// Start Azure VM
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> StartVm(string id)
        {
            var customVm = await _context.CustomVms
                .FirstOrDefaultAsync(m => m.Name == id);
            if (customVm == null)
            {
                return NotFound();
            }
            
            azureVmService.StartAzureVm(id);
            customVm.IsStarted = true;
            _context.Update(customVm);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> StopVm(string id)
        {
            var customVm = await _context.CustomVms
                .FirstOrDefaultAsync(m => m.Name == id);
            if (customVm == null)
            {
                return NotFound();
            }
            
            azureVmService.StopAzureVm(id);
            customVm.IsStarted = false;
            _context.Update(customVm);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool CustomVmExists(string id)
        {
          return (_context.CustomVms.Any(e => e.Login == id));
        }
    }
}

WebApp/Gaming/Controllers/HomeController.cs
using Azure;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Compute;
using Azure.ResourceManager.Compute.Models;
using Azure.ResourceManager.Network;
using Azure.ResourceManager.Network.Models;
using Azure.ResourceManager.Resources;
using Gaming.Models;
using Gaming.Services;
using Microsoft.AspNetCore.Mvc;

namespace Gaming.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private const string Location = "France Central";
    private const string ResourceGroupName = "rg-gaming-vm-001";

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
}

WebApp/Gaming/Views/CustomVm/Create.cshtml
@model Gaming.Models.CustomVm

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CustomVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Gaming/Views/CustomVm/Delete.cshtml
@model Gaming.Models.CustomVm

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomVm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsStarted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsStarted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Login" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Gaming/Views/CustomVm/Details.cshtml
@model Gaming.Models.CustomVm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CustomVm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsStarted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsStarted)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Login">Edit</a> |
    <a asp-action="StopVm" asp-route-id="@Model?.Login">Stop</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Gaming/Views/CustomVm/Edit.cshtml
@model Gaming.Models.CustomVm

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CustomVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Login" />
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ip" class="control-label"></label>
                <input asp-for="Ip" class="form-control" />
                <span asp-validation-for="Ip" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsStarted" /> @Html.DisplayNameFor(model => model.IsStarted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Gaming/Views/CustomVm/Index.cshtml
@model IEnumerable<Gaming.Models.CustomVm>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsStarted)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr class="align-middle">
            <td>
                @Html.DisplayFor(modelItem => item.Login)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsStarted)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Login"><i class="bi bi-pen"></i></a>
                @if (!item.IsStarted)
                {
                    <a class="btn btn-success" asp-action="StartVm" asp-route-id="@item.Name" asp-controller="CustomVm"><i class="bi bi-play"></i></a>
                }
                else
                {
                    <a class="btn btn-warning" asp-action="StopVm" asp-route-id="@item.Name" asp-controller="CustomVm"><i class="bi bi-stop"></i></a>
                    <a class="btn btn-success" href="ssh://@item.Login@@@item.Ip">SSH</a>
                    <a class="rdp-file btn btn-success" data-ip="@item.Ip" data-username="@item.Login" data-password="@item.Password">RDP</a>
                }
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Login"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
    }
    </tbody>
</table>

<script>
    
const buttons = document.querySelectorAll(".rdp-file")

buttons.forEach((btn)=>{
    btn.addEventListener('click', (ev)=>{
        const target = ev.target
        const ip = target.getAttribute('data-ip')
        const [username, password] = [target.getAttribute('data-username'), target.getAttribute('data-password')]
        rdpFile(ip, username, password)
    })    
})

const rdpFile = (ip, username, password) =>{
    
    const link = document.createElement("a");
    const file = new Blob([`full address:s:${ip}\nusername:s:${username}\npassword:s:${password}`], { type: 'text/plain' }); 
    link.href = URL.createObjectURL(file);
    link.download = `${ip}.rdp`;
    link.click(); 
}
   
    
</script>

WebApp/Gaming/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Gaming/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Gaming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebAppTest.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gaming</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.Identity.IsAuthenticated) {
                      <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CustomVM" asp-action="Index">VM</a>
                      </li>                   
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - Gaming - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>